//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blue_Print
    {
        public long ID { get; set; }
        public Nullable<int> Main_ID { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public string OfficeName { get; set; }
        public string Child_Care { get; set; }
        public string Civil_Litigation { get; set; }
        public string Clinical_Negligence { get; set; }
        public string Community_Care { get; set; }
        public string Crime { get; set; }
        public string Employment { get; set; }
        public string Housing { get; set; }
        public string Immigration { get; set; }
        public string Mental_Health { get; set; }
        public string Personal_Injury { get; set; }
        public string Prison_Law { get; set; }
        public string Public_Law { get; set; }
        public string Welfare_Benefits { get; set; }
        public string Business_Immigration { get; set; }
        public string Mental_capacity { get; set; }
        public string Action_Against_Public_Authorities { get; set; }
        public string Court_of_Protection { get; set; }
        public string Motoring_Law { get; set; }
        public string Wills_and_Probate { get; set; }
        public string International_Disputes { get; set; }
        public string Commercial { get; set; }
        public string Islamic_Law { get; set; }
    }
}
