//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReferral
    {
        public long ID { get; set; }
        public int Step { get; set; }
        public string FeeEarner { get; set; }
        public string FeeEarnerDepartment { get; set; }
        public string Clientname { get; set; }
        public string Client_email { get; set; }
        public Nullable<long> Client_Mob { get; set; }
        public string Client_tel { get; set; }
        public string Client_Nationality { get; set; }
        public string Date_Claimed_Asylum { get; set; }
        public string Date_Asylum_Interview { get; set; }
        public string ClientRef { get; set; }
        public string MatterNo { get; set; }
        public string Interpreter_Required { get; set; }
        public string Description { get; set; }
        public string Ref_SubDepartment { get; set; }
        public string Ref_Department { get; set; }
        public Nullable<decimal> NewClient_Date { get; set; }
        public string Cat { get; set; }
        public string Location { get; set; }
        public string Ref_Director { get; set; }
        public string Ref_Description { get; set; }
        public Nullable<System.DateTime> DateRef1 { get; set; }
        public string Ref_Feeearner { get; set; }
        public string Dir_Description { get; set; }
        public Nullable<System.DateTime> DateRef2 { get; set; }
        public string NewClientRef { get; set; }
        public string NewMatterRef { get; set; }
        public string New_FeeEarner { get; set; }
        public Nullable<System.DateTime> DateRef3 { get; set; }
        public string Reason_Refusal { get; set; }
        public Nullable<bool> HR_Approval { get; set; }
        public string FeeEarner_Response { get; set; }
        public string Urgency { get; set; }
        public string Language_Needs { get; set; }
        public string Source1 { get; set; }
        public string Source { get; set; }
        public string ip_address { get; set; }
        public string Referral_to { get; set; }
        public string Confirmed { get; set; }
        public string Cancel { get; set; }
        public string RoomBooked { get; set; }
        public string FeedbackafterAppointment { get; set; }
        public string Reason_Cancel { get; set; }
        public string Fee_Earner_Attendance { get; set; }
        public string Attendance_Confirmed_By { get; set; }
        public string Filename { get; set; }
        public string CustomerServiceMember { get; set; }
        public string Preferred_Location { get; set; }
        public string DetentionCenter { get; set; }
        public string Client_Forename { get; set; }
        public string Client_Surname { get; set; }
        public string Client_Postcode { get; set; }
        public string Legal_Private { get; set; }
        public string CFA { get; set; }
        public string Insurance { get; set; }
        public string matter_allocated_notes { get; set; }
        public string cancel_Signposted { get; set; }
        public string Step3_Action { get; set; }
        public Nullable<bool> New_old_Client { get; set; }
        public string detained { get; set; }
        public string Module { get; set; }
        public Nullable<decimal> IRC_Surgery_ID { get; set; }
        public string ModeOfCommunication { get; set; }
        public string ActoinedBy { get; set; }
        public Nullable<System.DateTime> ActionedDate { get; set; }
        public Nullable<int> HousingDisrepairCalculatorId { get; set; }
        public string SwitchboardCallBackRequired { get; set; }
        public string SwitchboardCallBackNotes { get; set; }
        public string SwitchboardCallBackStaffName { get; set; }
        public Nullable<System.DateTime> SwitchboardCallbackDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> WarningColorCode { get; set; }
        public string WarningMessage { get; set; }
        public Nullable<bool> IndigoMatterOpen { get; set; }
        public Nullable<bool> IndigoMatterNotOpenReason { get; set; }
        public string Cancel_Category { get; set; }
    }
}
