//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internship
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string LPC { get; set; }
        public string BVC { get; set; }
        public string LLB { get; set; }
        public string Filename1 { get; set; }
        public string Filename2 { get; set; }
        public Nullable<System.DateTime> Date_Available { get; set; }
        public string Duration { get; set; }
        public string Mon_ST { get; set; }
        public string Mon_ET { get; set; }
        public string Tue_ST { get; set; }
        public string Tue_ET { get; set; }
        public string Wed_ST { get; set; }
        public string Wed_ET { get; set; }
        public string Thu_ST { get; set; }
        public string Thu_ET { get; set; }
        public string Fri_ST { get; set; }
        public string Fri_ET { get; set; }
        public string Comments { get; set; }
        public string Area1 { get; set; }
        public string Area2 { get; set; }
        public string Area3 { get; set; }
        public string Office1 { get; set; }
        public string Office2 { get; set; }
        public string Office3 { get; set; }
        public string Status { get; set; }
        public string Accepted_Area { get; set; }
        public string Accepted_Office { get; set; }
        public string Accepted_StartDate { get; set; }
        public string Accepted_Supervisor { get; set; }
        public string Filename_Passport { get; set; }
        public string Accepted_By { get; set; }
        public Nullable<System.DateTime> Actual_Start_Date { get; set; }
        public Nullable<System.DateTime> Work_Assesment_Date { get; set; }
        public string Work_Assesment_Filename { get; set; }
        public Nullable<System.DateTime> Reject_Date { get; set; }
        public string Reject_Reason { get; set; }
        public Nullable<System.DateTime> Date_Applied { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string Answer4 { get; set; }
        public string Answer5 { get; set; }
        public string Answer6 { get; set; }
        public string Answer7 { get; set; }
        public string Answer8 { get; set; }
        public string Answer9 { get; set; }
        public string Answer10 { get; set; }
        public string Answer11 { get; set; }
        public string Answer12 { get; set; }
        public string Answer13 { get; set; }
        public string Answer14 { get; set; }
        public string Answer16 { get; set; }
        public string Answer17 { get; set; }
        public string Answer18 { get; set; }
        public string Answer19 { get; set; }
        public string Answer20 { get; set; }
        public string Answer21 { get; set; }
        public string Answer22 { get; set; }
        public string Answer23 { get; set; }
        public string Answer24 { get; set; }
        public string Answer25 { get; set; }
        public string Answer26 { get; set; }
        public string Answer1A { get; set; }
        public string Answer2A { get; set; }
        public string Answer3A { get; set; }
        public string Answer4A { get; set; }
        public string Answer5A { get; set; }
        public string Answer6A { get; set; }
        public string Answer7A { get; set; }
        public string Answer8A { get; set; }
        public string Answer9A { get; set; }
        public string Answer10A { get; set; }
        public string Answer11A { get; set; }
        public string Answer12A { get; set; }
        public string Answer13A { get; set; }
        public string Answer14A { get; set; }
        public string Answer16A { get; set; }
        public string Answer17A { get; set; }
        public string Answer18A { get; set; }
        public string Answer19A { get; set; }
        public string Answer20A { get; set; }
        public string Answer21A { get; set; }
        public string Answer22A { get; set; }
        public string Answer23A { get; set; }
        public string Answer24A { get; set; }
        public string Answer25A { get; set; }
        public string Answer26A { get; set; }
        public string Answer15 { get; set; }
        public string Answer15A { get; set; }
        public string Answer27 { get; set; }
        public string Accepted_Duration { get; set; }
        public byte[] Cover_Letter { get; set; }
        public byte[] CV { get; set; }
        public byte[] Passport { get; set; }
    }
}
