//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public string Appointment { get; set; }
        public string Postcode { get; set; }
        public string Google_Map_String { get; set; }
        public string In_Out_London { get; set; }
        public string Picture { get; set; }
        public string OfficeCode { get; set; }
        public string County { get; set; }
        public string Dedicated_Numbers { get; set; }
        public string Business_Cards_Address { get; set; }
        public Nullable<bool> RoomBooking { get; set; }
        public string Company { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
