//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long ID { get; set; }
        public string ClientReference { get; set; }
        public string ClientName { get; set; }
        public string Caseworker { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string Payment_Status { get; set; }
        public string Email { get; set; }
    }
}
