//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public int ID { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public string Post_Title { get; set; }
        public Nullable<System.DateTime> Date_CV { get; set; }
        public string Agency { get; set; }
        public string Filename { get; set; }
        public byte[] Evidence { get; set; }
        public string Notes { get; set; }
        public string Added_By { get; set; }
        public string Interview_By { get; set; }
        public string Time_interview { get; set; }
        public Nullable<System.DateTime> Date_Interview { get; set; }
        public string Updated_By { get; set; }
        public string Interview_Outcome { get; set; }
        public string Interview_Outcome_Notes { get; set; }
        public string Outcome_UpdatedBy { get; set; }
        public Nullable<System.DateTime> Date_Offered { get; set; }
        public string Date_Offered_Updated { get; set; }
        public Nullable<System.DateTime> Date_LetterRequested { get; set; }
        public string Requested_By { get; set; }
        public Nullable<System.DateTime> Date_Offered_Sent { get; set; }
        public string Offer_Sent_Updated { get; set; }
        public Nullable<System.DateTime> Date_Acceptance_Recieved { get; set; }
        public string Acceptance_Updated { get; set; }
        public Nullable<System.DateTime> Date_Started { get; set; }
        public Nullable<System.DateTime> Date_Archived { get; set; }
        public string Archived_By { get; set; }
        public string Tel { get; set; }
        public string Mob { get; set; }
        public string Address { get; set; }
        public string Qualification { get; set; }
        public string DOB { get; set; }
        public string NI_Number { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public string Salary { get; set; }
        public string Supervisor { get; set; }
        public string Department { get; set; }
        public string Office { get; set; }
        public string Special_Conditions { get; set; }
        public string admitted_staff { get; set; }
        public string Probation_Period { get; set; }
        public string Email { get; set; }
        public string Filename_CoverLetter { get; set; }
        public Nullable<int> Job_ID { get; set; }
        public string Source { get; set; }
        public string Title { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string post_code { get; set; }
        public string address2 { get; set; }
        public string emp_skype_id { get; set; }
        public string corpost_code { get; set; }
        public Nullable<bool> Applicant_status { get; set; }
        public string status_updatedBy { get; set; }
        public Nullable<System.DateTime> status_updatedOn { get; set; }
        public string Reference_id { get; set; }
        public Nullable<bool> Hr_status { get; set; }
        public Nullable<int> Count { get; set; }
        public string Remark { get; set; }
        public byte[] Passport { get; set; }
        public byte[] Practicing { get; set; }
        public string emp_code { get; set; }
        public string management_approval { get; set; }
        public string management_comments { get; set; }
        public string main_add_line1 { get; set; }
        public string main_add_line2 { get; set; }
        public string main_add_line3 { get; set; }
        public string main_add_town { get; set; }
        public string main_add_county { get; set; }
        public string corr_add_line1 { get; set; }
        public string corr_add_line2 { get; set; }
        public string corr_add_line3 { get; set; }
        public string corr_add_town { get; set; }
        public string corr_add_county { get; set; }
        public string Bank_Name { get; set; }
        public string bank_address { get; set; }
        public string bank_acc_name { get; set; }
        public string bank_acc_no { get; set; }
        public string bank_sort_code { get; set; }
        public string next_of_kin_1 { get; set; }
        public string next_of_kin_relationship { get; set; }
        public string next_of_kin_1_address_1 { get; set; }
        public string next_of_kin_1_tel_no { get; set; }
        public string next_of_kin_1_mbile_no { get; set; }
        public string next_of_kin_1_address_2 { get; set; }
        public string nationality { get; set; }
        public string visa_type { get; set; }
        public string visa_expiry_date { get; set; }
        public string nonadmitted_staff { get; set; }
        public string admin_staff { get; set; }
        public string freelance_consultant { get; set; }
        public string limited_company { get; set; }
        public string qualifications { get; set; }
        public Nullable<System.DateTime> date_admitted { get; set; }
        public string sra_number { get; set; }
        public string Currentpractising_certificate { get; set; }
        public string law_degree { get; set; }
        public string law_degree_result { get; set; }
        public string copy_of_degree_given { get; set; }
        public string qltt_grade { get; set; }
        public Nullable<System.DateTime> qltt_date { get; set; }
        public string qltt_received { get; set; }
        public string lpc_gained { get; set; }
        public Nullable<System.DateTime> lpc_gained_date { get; set; }
        public string lpc_gained_university { get; set; }
        public string lpc_result { get; set; }
        public string copy_of_lpc_given { get; set; }
        public string bvc_gained { get; set; }
        public Nullable<System.DateTime> bvc_gained_date { get; set; }
        public string bvc_gained_university { get; set; }
        public string bvc_result { get; set; }
        public string copy_of_bvc_given { get; set; }
        public string law_degree_gained_university { get; set; }
        public string previous_organisation { get; set; }
        public Nullable<System.DateTime> date_left_prev_org { get; set; }
        public string prev_org_address { get; set; }
        public string admitted_staff_old2 { get; set; }
        public string IsPractising_Condition { get; set; }
        public string Practising_Condn_Details { get; set; }
        public string FamilyLawPanel { get; set; }
        public string ChildLawPanel { get; set; }
        public string CrimeDutyPanel { get; set; }
        public string ImmigrationPanel { get; set; }
        public string MentalHealthPanel { get; set; }
        public string OtherPanel { get; set; }
        public string Recruit_Dir { get; set; }
        public string Director_Approval { get; set; }
        public string Director_Comments { get; set; }
        public string file_downloaded { get; set; }
    }
}
