//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment_DlWeb
    {
        public int Job_Ref_Code { get; set; }
        public string Job_Brief_Description { get; set; }
        public string Department { get; set; }
        public string Job_Title { get; set; }
        public string Job_Description { get; set; }
        public string Key_Skills_Required { get; set; }
        public System.DateTime Date_Posted { get; set; }
        public string Location { get; set; }
        public string Job_Type { get; set; }
        public int Visited_Count { get; set; }
        public int Sequence { get; set; }
        public string Salary { get; set; }
        public string email { get; set; }
        public bool Live_Inhouse { get; set; }
        public bool Live { get; set; }
        public string EssentialCriteria1 { get; set; }
        public string EssentialCriteria2 { get; set; }
        public string EssentialCriteria3 { get; set; }
        public string EssentialCriteria4 { get; set; }
        public string Agencies { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Agency1 { get; set; }
        public string Agency2 { get; set; }
        public string Agency3 { get; set; }
        public string Agency4 { get; set; }
        public string Agency5 { get; set; }
        public Nullable<System.DateTime> S_Date1 { get; set; }
        public Nullable<System.DateTime> S_Date2 { get; set; }
        public Nullable<System.DateTime> S_Date3 { get; set; }
        public Nullable<System.DateTime> S_Date4 { get; set; }
        public Nullable<System.DateTime> S_Date5 { get; set; }
        public Nullable<System.DateTime> E_Date1 { get; set; }
        public Nullable<System.DateTime> E_Date2 { get; set; }
        public Nullable<System.DateTime> E_Date3 { get; set; }
        public Nullable<System.DateTime> E_Date4 { get; set; }
        public Nullable<System.DateTime> E_Date5 { get; set; }
        public string Keywords { get; set; }
        public string Created_user { get; set; }
        public string Created_version { get; set; }
        public Nullable<System.DateTime> Created_stamp { get; set; }
        public string Created_Program { get; set; }
        public string Created_machine_name { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> modified_stamp { get; set; }
        public string modified_ueser { get; set; }
        public string modified_version { get; set; }
        public string modified_program { get; set; }
        public string modified_machine_name { get; set; }
        public string modified_ip { get; set; }
        public string emp_code { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string Duncanlewis_Desc { get; set; }
        public string Department_Desc { get; set; }
        public string Rewards { get; set; }
        public string VacancyRole { get; set; }
        public string Equal_Opportunities { get; set; }
        public string Recruit_Job_ID { get; set; }
        public string FIlename { get; set; }
    }
}
