//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Details
    {
        public string forename { get; set; }
        public string surname { get; set; }
        public string department_it { get; set; }
        public string office_name { get; set; }
        public string admitted_staff { get; set; }
        public string nonadmitted_staff { get; set; }
    }
}
