//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubDepartment
    {
        public string Department { get; set; }
        public string SubDepartment1 { get; set; }
        public int ID { get; set; }
        public string SubDepartment_Switchboard { get; set; }
        public string email { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> DelayOpeningToAllOffices { get; set; }
    }
}
