//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trustpilot_Webhooks
    {
        public int Id { get; set; }
        public string EventId { get; set; }
        public string Language { get; set; }
        public Nullable<int> Stars { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string LocationId { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string ConsumerId { get; set; }
        public string ConsumerName { get; set; }
    }
}
