//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLWebsiteWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoCallRequest
    {
        public int Id { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string ZoommailId { get; set; }
        public string Telephone { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Timeslot { get; set; }
        public string Status { get; set; }
        public string Topic { get; set; }
        public string Agenda { get; set; }
        public string DLZoomAccount { get; set; }
        public string NotesForClient { get; set; }
        public string AcceptedBy { get; set; }
        public string MeetingID { get; set; }
        public string start_url { get; set; }
    }
}
